name: Run Python Script

# on:
#   schedule:
#     - cron: "0 */2 * * *" # Run every two hours

on:
  schedule:
    - cron: "*/2 * * * *" # Run every two minutes

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python script.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@example.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update dataset from Python script"
          git push
